# Site settings
title: Katja Hollaar
email: afkatja@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Example profile with wheelhouse for github patchwork
baseurl: "/patchwork-gh-pages-24"
url: "http://katjahollaar.github.io"
twitter_username: afkatja
github_username:  afkatja
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
